apiVersion: apps/v1
kind: Deployment
metadata:
  name: secret-test-api-deployment
spec:
  selector:
    matchLabels:
      app: secret-test-api
  template:
    metadata:
      labels:
        app: secret-test-api    
    spec:
      containers:
      - name: secret-test-api
        image: secrettest:latest
        imagePullPolicy: Never
        resources:
          requests:
            memory: "50Mi"
            cpu: "50m"
          limits:
            memory: "100Mi"
            cpu: "100m"
        ports:
        - containerPort: 80
        env:
          - name: RabbitMqConfig__Host
            valueFrom:
              secretKeyRef:
                name: azure-kv-secrets        # name of secretObject in SecretProviderClass
                key: rabbitmq_host            # name of key in secretObject         
          - name: RabbitMqConfig__Username
            valueFrom:
              secretKeyRef:
                name: azure-kv-secrets        # name of secretObject in SecretProviderClass
                key: rabbitmq_username        # name of key in secretObject         
          - name: RabbitMqConfig__Password
            valueFrom:
              secretKeyRef:
                name: azure-kv-secrets        # name of secretObject in SecretProviderClass
                key: rabbitmq_password        # name of key in secretObject         
        volumeMounts:
          - name: appsettings-volume
            mountPath: /App/appsettings.json
            subPath: appsettings.json
          - name: azure-secrets-mount         # mount is still needed so driver creates secretObject
            mountPath: /mnt/secrets-store
            readOnly: true
      volumes:
        - name: appsettings-volume
          configMap:
            name: appsettings
        - name: azure-secrets-mount
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "<keyvault-name>"
            nodePublishSecretRef:
              name: secrets-store-creds