apiVersion: apps/v1
kind: Deployment
metadata:
  name: secret-test-api-deployment
spec:
  selector:
    matchLabels:
      app: secret-test-api
  template:
    metadata:
      labels:
        app: secret-test-api    
    spec:
      containers:
      - name: secret-test-api
        image: secrettest:latest
        imagePullPolicy: Never
        resources:
          requests:
            memory: "50Mi"
            cpu: "50m"
          limits:
            memory: "100Mi"
            cpu: "100m"
        ports:
        - containerPort: 80
        env:
          - name: RabbitMqConfig__Host
            valueFrom:
              secretKeyRef:
                key: rabbitmq_host
                name: azure-kv-secrets
          - name: RabbitMqConfig__Username
            valueFrom:
              secretKeyRef:
                key: rabbitmq_username
                name: azure-kv-secrets
          - name: RabbitMqConfig__Password
            valueFrom:
              secretKeyRef:
                key: rabbitmq_password
                name: azure-kv-secrets
        volumeMounts:
          - name: appsettings-volume
            mountPath: /App/appsettings.json
            subPath: appsettings.json
          - name: azure-secrets-mount
            mountPath: /mnt/secrets-store
            readOnly: true
      volumes:
        - name: appsettings-volume
          configMap:
            name: appsettings
        - name: azure-secrets-mount
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "kv-secret-test"
            nodePublishSecretRef:
              name: secrets-store-creds