apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: <keyvault-name>
spec:
  provider: azure
  secretObjects:                                 # [OPTIONAL] SecretObject defines the desired state of synced K8s secret objects
  - secretName: azure-kv-secrets
    type: Opaque
    data: 
    - objectName: RabbitMq-Host                  # name of the mounted content to sync. this could be the object name or object alias 
      key: rabbitmq_host
    - objectName: RabbitMq-Username              # name of the mounted content to sync. this could be the object name or object alias 
      key: rabbitmq_username
    - objectName: RabbitMq-Password              # name of the mounted content to sync. this could be the object name or object alias 
      key: rabbitmq_password
  parameters:
    usePodIdentity: "false"
    keyvaultName: "<keyvault-name>"
    objects:  |
      array:
        - |
          objectName: RabbitMq-Host
          objectType: secret                     # object types: secret, key or cert
          objectVersion: ""                      # [OPTIONAL] object versions, default to latest if empty
        - |
          objectName: RabbitMq-Username
          objectType: secret                     # object types: secret, key or cert
          objectVersion: ""                      # [OPTIONAL] object versions, default to latest if empty
        - |
          objectName: RabbitMq-Password
          objectType: secret                     # object types: secret, key or cert
          objectVersion: ""                      # [OPTIONAL] object versions, default to latest if empty
    tenantId: "<tenantId>"